# Generated by Django 2.2 on 2020-07-10 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('kode', models.CharField(max_length=3)),
                ('ibukota', models.CharField(blank=True, max_length=30)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.CreateModel(
            name='kabkot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Kabupaten', 'Kabupaten'), ('Kota', 'Kota')], max_length=10)),
                ('nama', models.TextField(max_length=100)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('keterangan', models.TextField(blank=True)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid.Provinsi')),
            ],
            options={
                'verbose_name': 'kabupaten/kota',
                'verbose_name_plural': 'kabupaten/kota',
            },
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('indexaktifkawalcovid', models.DecimalField(decimal_places=10, max_digits=19)),
                ('indexmovemennt', models.DecimalField(decimal_places=10, max_digits=19)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid.Provinsi')),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='hargapangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komoditas', models.CharField(choices=[('Beras', 'Beras'), ('Daging Ayam', 'Daging Ayam'), ('Daging Sapi', 'Daging Sapi'), ('Telur Ayam', 'Telur Ayam'), ('Bawang Merah', 'Bawang Merah'), ('Bawang Putih', 'Bawang Putih'), ('Cabai Merah', 'Cabai Merah'), ('Cabai Rawit', 'Cabai Rawit'), ('Minyak Goreng', 'Minyak Goreng'), ('Gula Pasir', 'Gula Pasir')], default='Beras', max_length=30)),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('harga', models.IntegerField()),
                ('keterangan', models.TextField(blank=True)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid.Provinsi')),
            ],
            options={
                'verbose_name': 'Harga Pangan',
                'verbose_name_plural': 'harga Pangan',
            },
        ),
        migrations.CreateModel(
            name='covid19provinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('terkonfirmasi', models.IntegerField()),
                ('perawatan', models.IntegerField()),
                ('sembuh', models.IntegerField()),
                ('meninggal', models.IntegerField()),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid.Provinsi')),
            ],
            options={
                'verbose_name': 'Pasien Provinsi',
                'verbose_name_plural': 'pasien Provinsi',
            },
        ),
    ]
