# Generated by Django 3.0.8 on 2020-07-25 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200725_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikelcov',
            name='topik',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='covid.topikArtikel'),
            preserve_default=False,
        ),
    ]
