# Generated by Django 3.0.8 on 2021-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_artikelcov_topik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveysetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('persepsi_kebijakan', models.CharField(blank=True, max_length=1000)),
                ('pengetahuan_kepatuhan', models.CharField(blank=True, max_length=1000)),
                ('tanggungjawab_sosial', models.CharField(blank=True, max_length=1000)),
                ('persepsi_kekhawatiran', models.CharField(blank=True, max_length=1000)),
                ('persepsi_vaksin', models.CharField(blank=True, max_length=1000)),
                ('dampak_ekonomi', models.CharField(blank=True, max_length=1000)),
                ('demografi', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
