# Generated by Django 3.0.8 on 2021-02-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_surveysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysetting',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
